version: '3'
volumes:
 dbdata: 

networks:
 default:

services:

  admin-ui:
    image: jrsaravanan/customer-admin
    container_name: admin-ui
    ports: 
      -  9000:9000 
   
  discovery:
   image: jrsaravanan/customer-discovery
   container_name: discovery
   environment:
    CUSTOMER_ADMIN_URI: http://admin-ui:9000/
   ports:
    - 8761
   depends_on:
    - admin-ui
   
  customer-service:
   image: jrsaravanan/customer-service
   environment:
    CUSTOMER_APP_USER: appuser
    CUSTOMER_APP_PASSWORD: appuser
    CUSTOMER_DB_URI: customerdb:3306/customers
    CUSTOMER_ADMIN_URI: http://admin-ui:9000/
    DISCOVERY_URI: http://discovery:8761/eureka
    SLEEP_LENGTH: 1.0   
   ports:
    - 8080
   depends_on:
    - customerdb
    - admin-ui
    - discovery 

  auth-service:
   image: jrsaravanan/customer-auth
   environment:
    AUTH_APP_USER: appuser
    AUTH_APP_PASSWORD: appuser
    AUTH_DB_URI: 'customer-auth-db:3306/auth'
    CUSTOMER_ADMIN_URI: http://admin-ui:9000/
    DISCOVERY_URI: http://discovery:8761/eureka
    INIT_DB: 'true' 
    PORT: 8080
    SLEEP_LENGTH: 0.5  
   ports:
    - 8080
   depends_on:
    - customer-auth-db
    - admin-ui
    - discovery   

  customerdb:
   image: mysql:5.6
   container_name: customerdb
   environment:
     MYSQL_ROOT_PASSWORD: admin
     MYSQL_DATABASE: customers
     MYSQL_USER: appuser
     MYSQL_PASSWORD: appuser  
     MYSQL_ROOT_PASSWORD: appuser     
   ports:
     - 3306:3306

       
  customer-auth-db:
   image: mysql:5.6
   container_name: customer-auth-db
   environment:
     MYSQL_ROOT_PASSWORD: admin
     MYSQL_DATABASE: auth
     MYSQL_USER: appuser
     MYSQL_PASSWORD: appuser  
     MYSQL_ROOT_PASSWORD: appuser     
   ports:
     - 13306:3306

  api-service:
   image: jrsaravanan/customer-edge-service
   environment:
    CUSTOMER_ADMIN_URI: http://admin-ui:9000/
    DISCOVERY_URI: http://discovery:8761/eureka
    PORT: 8080
   ports:
    - 8080
   depends_on:
    - discovery    
    - auth-service
    - customer-service

