server:
  port: ${PORT:0}

spring:
  application:
    name: Customer-Service
  boot:
   admin:
    url: ${CUSTOMER_ADMIN_URI:http://localhost:9000 }

management:
 security:
  enabled: false    

logging:
  file: logs/customer-service.log

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9090/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.int}

