server:
  port: ${PORT:9090}

spring:
  application:
    name: Customer-Discovery-Service

logging:
  file: logs/customer-discovery-service.log

eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false