server:
  port: ${PORT:9090}

spring:
  application:
    name: api-service
  boot:
   admin:
    url: ${CUSTOMER_ADMIN_URI:http://localhost:9000 }  

logging:
  level: 
   ROOT: info
  file: logs/customer-edge-service.log

eureka:
 client:
  enabled: true
  registerWithEureka: false
  fetchRegistry: true
  serviceUrl:
   defaultZone: ${DISCOVERY_URI:http://127.0.0.1:8761/eureka}
  server:
    enableSelfPreservation: false

ribbon:
 eureka:
  enabled: true
  
management:
  security:
    enabled: false

zuul:
 routes:
  
  auth-service:
   sensitiveHeaders:
   path: /uaa/**
   serviceId: auth-service
   stripPrefix: false
  
  customer-service:
   path: /v1.0/customers/**
   serviceId: customer-service
   stripPrefix: false   

auth-service:
 url: http://auth-service/v1.0/auth
 
security:
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
  client:
   accessTokenUri: ${AUTH_LOGIN_URI:http://127.0.0.1:8070/uaa/oauth/token}
   userAuthorizationUri: ${AUTH_VAL_URI:http://127.0.0.1:8070/uaa/oauth/authorize}
   clientId: html5
   clientSecret: password
  resource:
   userInfoUri: ${AUTH_USER_URI:http://1270.01:8070/uaa/oauth/user}
   preferTokenInfo: false
  session: ALWAYS
  